### ISSUE TITLE
Bug: Handle PHP_INT_MAX overflow

### ISSUE THREAD

**Issue by caendesilva** [RobThree/HumanoID#9]
Sorry for all the tickets I'm creating, but I am loving the package so far and want to help improve it :)

This bug has a pretty low chance of surfacing in actual use but the fix is simple enough so I thought I'd mention it.

Description:
Supplying a value larger than a signed 64bit integer to the create method causes a type error.

Steps to reproduce:
```php
$generator = HumanoIDs::spaceIdGenerator();
$id = $generator->create(PHP_INT_MAX + 1);
```

Which throws the following error:
```
RobThree\HumanoID\HumanoID::create(): Argument #1 ($id) must be of type int, float given,
```

Expected output:
Since https://github.com/RobThree/HumanoID/blob/master/src/HumanoID.php#L116 checks for negative values and throws an InvalidArgumentException, something similar would be expected.

However, since the error happens before the check even happens I'm not sure how it would be implemented without changing the argument type. And it seems counter productive to allow floats just to throw an exception that floats are not allowed.

**Comment by RobThree** [comment]
The `PHP_INT_MAX` is thrown by PHP itself since you're trying to fit a square peg in a round hole (i.e. a float into an int). This is what typing and compile-time-checking is for. This is, IMHO, normal and _expected_ behavior and I don't see the need (nor a sane way) to "fix" this. This is gonna be a won'tfix I'm afraid unless someone more knowledgeable in PHP has a better suggestion.

**Comment by caendesilva** [comment]
Yeah, I kinda realized that myself while writing the issue so assumed this would not be changed so no hard feelings here. Just thought I could let you know while I had already written it up :)  I love the square peg in a round hole analogy by the way!
